name: froggie-_-pr

on:
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/setup-node@v3.4.1
      with:
        node-version: 16.15.1
    - uses: actions/checkout@v3
    - name: download-packages
      run: npm update
    - name: build
      run: npm run build
    - name: install-zip
      run: sudo apt-get install -y zip
    - name: zip-dist
      run: sudo zip -r dist.zip ./dist/
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: az storage blob upload-batch -s ./dist -d '$web' --account-name froggie --connection-string ${{ secrets.AZURE_FROGGIE_STORAGE_CONNECTION_STRING }}
