name: froggie-_-pr

on:
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.15.1
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install NPM Packages
        run: npm i
      - name: Generate Froggie API Client
        run: npm run genClient
      - name: Build
        run: npm run build
